backend/project2/src/main/java/com/team8/project2/domain/curation/controller/CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/entity/Curation.java, backend/project2/src/main/java/com/team8/project2/domain/curation/repository/CurationRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/link/controller/LinkController.java, backend/project2/src/main/java/com/team8/project2/domain/link/dto/LinkDTO.java, backend/project2/src/main/java/com/team8/project2/domain/link/entity/Link.java, backend/project2/src/main/java/com/team8/project2/domain/link/repository/LinkRepository.java, backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java
기초적인 CRUD 기능을 포함한 큐레이션과 링크의 entity, repository, service, controller을 추가했음
=> 큐레이션, 링크 entity, repository, service, controller 추가

backend/project2/.gitignore, backend/project2/src/main/resources/application-dev.yml, backend/project2/src/main/resources/application-prod.yml, backend/project2/src/main/resources/application-test.yml, backend/project2/src/main/resources/application.yml
개발, 테스트 편의를 위해 운영 환경과 분리합니다.
**환경에 따라 데이터 소스, 로그 설정 분리**
- 개발 환경 : H2 (update)
- 테스트 환경 : H2 (create-drop)
- 운영 환경 : MySql (none)
=> Feat/#15 개발, 테스트, 운영 환경분리

backend/project2/src/main/java/com/team8/project2/domain/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/entity/Curation.java, backend/project2/src/main/java/com/team8/project2/domain/curation/repository/CurationRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/link/controller/ApiV1LinkController.java, backend/project2/src/main/java/com/team8/project2/domain/link/entity/Link.java, backend/project2/src/main/java/com/team8/project2/domain/link/repository/LinkRepository.java, backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java
linkId와 curationId를 기존 방식이었던 string에서 잘라내서 분류하는 방법 말고 상속시켜서 분류하는 방식으로 바꿔 Long으로 id를 바꿈
=> Style/#18 change linkId, curationId to Long

backend/project2/src/main/java/com/team8/project2/Project2Application.java, backend/project2/src/main/java/com/team8/project2/domain/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/dto/CurationReqDTO.java, backend/project2/src/main/java/com/team8/project2/domain/curation/entity/Curation.java, backend/project2/src/main/java/com/team8/project2/domain/curation/entity/CurationLink.java, backend/project2/src/main/java/com/team8/project2/domain/curation/repository/CurationLinkRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/link/controller/ApiV1LinkController.java, backend/project2/src/main/java/com/team8/project2/domain/link/dto/LinkReqDTO.java, backend/project2/src/main/java/com/team8/project2/domain/link/entity/Link.java, backend/project2/src/main/java/com/team8/project2/domain/link/repository/LinkRepository.java, backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java, backend/project2/src/test/java/com/team8/project2/domain/curation/controller/ApiV1CurationControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/curation/service/CurationServiceTest.java, backend/project2/src/test/java/com/team8/project2/domain/link/service/LinkServiceTest.java
큐레이션과 링크의 연관관계를 나타내기 위한 큐레이션 링크 추가, 그에 맞게 기존 큐레이션 및 링크 엔티티, 서비스, 리포지토리, 컨트롤러 코드 리팩토링, 큐레이션, 링크 서비스 테스트 코드 추가(정상 작동 확인), 큐레이션 컨트롤러 테스트 코드 추가(정상 작동 확인)
=> Feat/#20 큐레이션, 링크 코드 리팩토링, 테스트 코드 작성

backend/.idea/modules/project2.iml, backend/.idea/modules/project2.main.iml, backend/.idea/modules/project2.test.iml, backend/project2/src/main/java/com/team8/project2/domain/playlist/service/PlaylistService.java, backend/project2/src/main/java/com/team8/project2/global/exception/BadRequestException.java, backend/project2/src/main/java/com/team8/project2/global/exception/GlobalExceptionHandler.java, backend/project2/src/main/java/com/team8/project2/global/exception/NotFoundException.java, backend/project2/src/test/java/com/team8/project2/domain/playlist/controller/ApiV1PlaylistControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/playlist/service/PlaylistServiceTest.java
- GlobalExceptionHandler에 NotFoundException 및 BadRequestException 추가
- 유닛테스트 진행
=> feat: GlobalExceptionHandler에 NotFoundException 및 BadRequestException 추가

backend/.idea/compiler.xml, backend/.idea/modules/project2.main.iml, backend/project2/build.gradle, backend/project2/src/main/java/com/team8/project2/global/security/SecurityConfig.java, backend/project2/src/main/java/com/team8/project2/global/springDocs/SpringDocsConfig.java
- SpringDocConfig를 추가하여 Swagger에서 API를 올바르게 인식하도록 설정.
- /swagger-ui/**, /v3/api-docs/** 경로에 대해 permitAll() 설정을 추가하여 인증 없이 접근 가능하도록 수정.
CORS 설정 개선
- Swagger 및 API 요청이 원활하게 처리되도록 CORS 허용 범위를 /api/**에서 /**로 확장.
=> Feat/#40 swagger UI

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/entity/Curation.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/entity/SearchOrder.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/repository/CurationRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/curation/like/entity/Like.java, backend/project2/src/test/java/com/team8/project2/domain/curation/controller/ApiV1CurationControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/curation/service/CurationServiceTest.java
- 사용자는 큐레이션에 ‘좋아요’를 누를 수 있으며, 큐레이션에 좋아요 수가 표시된다.
- 좋아요 중복 방지는 Member 작업이 완료되어야(인증 정보 사용 필요) 구현 가능
Closes #39
=> Feat/#39 큐레이션에 좋아요 기능 추가

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/entity/Curation.java, backend/project2/src/main/java/com/team8/project2/domain/curation/like/entity/Like.java, backend/project2/src/main/java/com/team8/project2/global/security/SecurityConfig.java
- 큐레이션 좋아요 기능 중 추가된 Like 엔티티의 테이블명이 DB 예약어라서 발생하던 오류 해결
- 큐레이션 API 테스트가 인증 설정으로 인해 실패하던 오류 해결(Curation API들을 Security 설정에서 허용)
Closes #43
=> Hotfix/#43 Like 엔티티의 테이블명이 DB 예약어라서 발생하던 오류 해결

backend/project2/src/main/java/com/team8/project2/domain/comment/controller/ApiV1CommentController.java, backend/project2/src/main/java/com/team8/project2/domain/comment/dto/CommentDto.java, backend/project2/src/main/java/com/team8/project2/domain/comment/entity/Comment.java, backend/project2/src/main/java/com/team8/project2/domain/comment/service/CommentService.java, backend/project2/src/main/java/com/team8/project2/domain/member/repository/MemberRepository.java, backend/project2/src/main/java/com/team8/project2/global/dto/RsData.java, backend/project2/src/main/java/com/team8/project2/global/exception/GlobalExceptionHandler.java, backend/project2/src/main/java/com/team8/project2/global/init/BaseInitData.java, backend/project2/src/main/java/com/team8/project2/global/security/SecurityConfig.java, backend/project2/src/test/java/com/team8/project2/domain/comment/controller/ApiV1CommentControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/curation/controller/ApiV1CurationControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/curation/service/CurationServiceTest.java
- Comment API 리팩토링
- 조회 시 작성자이름이 응답되도록 수정
- ServiceException 예외 핸들링 추가
- SecurityConfig에 Comment API 적용
- Comment 테스트 코드 추가
Closes #51
=> Refactor/#51 comment api 리팩토링

backend/project2/src/main/java/com/team8/project2/domain/link/controller/ApiV1LinkController.java, backend/project2/src/main/java/com/team8/project2/domain/link/dto/LinkResDTO.java, backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java, frontend/project2/app/components/header.tsx, frontend/project2/app/components/post-list.tsx
=> Feat/#54 메인페이지 필터링 기능 추가

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/curation/like/repository/LikeRepository.java, backend/project2/src/test/java/com/team8/project2/domain/curation/controller/ApiV1CurationControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/curation/service/CurationServiceTest.java
좋아요 기능 추가, 중복 좋아요 방지 및 좋아요 취소 기능
=> Feat/좋아요 기능 추가

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/repository/CurationRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/test/java/com/team8/project2/domain/curation/service/CurationServiceTest.java, frontend/project2/app/components/post-list.tsx, frontend/project2/package-lock.json, frontend/project2/package.json
메인페이지 각 큐레이션에 각 큐레이션이 갖고 있는 태그를 표시하고 태그를 선택하면 필터링된 큐레이션을 보여준다.
기존 리포지토리 코드에서는 선택된 태그들 중 하나만 갖고 있어도 반환하기 때문에 리포지토리에 새로운 코드를 추가해 선택된 태그가 있을때, 없을때로 분류하여 호출한다.
=> Feat/메인페이지 태그 표시 및 태그 필터링 기능 추가

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/test/java/com/team8/project2/domain/member/controller/ApiV1MemberControllerTest.java
메서드 누락으로 실패하던 `getCuratorInfoTest()` 테스트 수정
=> Fix/테스트 오류 수정

backend/project2/src/main/java/com/team8/project2/domain/member/controller/ApiV1MemberController.java, backend/project2/src/test/java/com/team8/project2/domain/member/controller/ApiV1MemberControllerTest.java
- 누락된 Test 코드 Merge
- MemberId로 Count를 하던 부분을 Username으로 변경
=> refactor: ApiV1MemberControllerTest MemberId -> Username

backend/project2/build.gradle, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/controller/ApiV1PlaylistController.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/service/PlaylistService.java, backend/project2/src/test/java/com/team8/project2/domain/playlist/controller/ApiV1PlaylistControllerTest.java, backend/project2/src/test/java/com/team8/project2/domain/playlist/service/PlaylistServiceTest.java
플레이리스트 추천 시스템을 개선하기 위해 Rule-Based 알고리즘을 추가
기존 태그 기반 추천 외에도 **조회수 및 좋아요 데이터를 활용한 가중치 추천**을 적용하여 **보다 정교한 추천이 가능하도록 개선** 
또한 **Redis 캐싱을 최적화하여** 성능을 향상시켰습니다.
=> Feat/#101 추천알고리즘 개선

frontend/project2/app/[username]/page.tsx, frontend/project2/app/components/comment-section.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/next.config.mjs
=> Hotfix/frontend build 오류 수정

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationDetailResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/entity/Curation.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationViewService.java, backend/project2/src/main/java/com/team8/project2/domain/link/controller/ApiV1LinkController.java, backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java, backend/project2/src/main/java/com/team8/project2/global/security/SecurityConfig.java, backend/project2/src/test/java/com/team8/project2/domain/link/service/LinkServiceTest.java, frontend/project2/app/components/header.tsx, frontend/project2/app/components/post-list.tsx, frontend/project2/app/curation/[id]/edit/page.tsx, frontend/project2/app/curation/[id]/page.tsx
메인, 상세 페이지 큐레이션 조회수 표시 및 갱신되는 거 확인
상세 페이지에 하트 버튼을 누르면 좋아요 API 호출
=> Feat/메인, 상세 페이지 큐레이션 조회수 표시

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationDetailResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/curation/like/repository/LikeRepository.java, backend/project2/src/main/java/com/team8/project2/global/Rq.java, frontend/project2/app/components/comment-section.tsx, frontend/project2/app/components/post-list.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/curation/following/page.tsx
좋아요 조회 방법을 큐레이션 응답에 포함하도록 변경하고, front에서 쿠키를 포함하지 않는 오류를 수정했습니다.
=> Feat/좋아요 기능 큐레이션 응답에 포함

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationDetailResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/repository/CurationRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/member/controller/ApiV1MemberController.java, backend/project2/src/main/java/com/team8/project2/domain/member/dto/CuratorInfoDto.java, backend/project2/src/main/java/com/team8/project2/domain/member/dto/FollowResDto.java, backend/project2/src/main/java/com/team8/project2/domain/member/dto/UnfollowResDto.java, backend/project2/src/main/java/com/team8/project2/domain/member/entity/Follow.java, backend/project2/src/main/java/com/team8/project2/domain/member/repository/FollowRepository.java, backend/project2/src/main/java/com/team8/project2/domain/member/service/MemberService.java, frontend/project2/app/[username]/page.tsx, frontend/project2/app/components/header.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/following/page.tsx
**글 상세 페이지에서 팔로우 기능 연결**
**큐레이터 페이지에서 팔로우 기능 연결**
**팔로잉 페이지 구현 및 연결, 레이아웃 헤더 수정**
Closes #118
=> Feat/#118 팔로우 기능 연결

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, backend/project2/src/main/java/com/team8/project2/domain/curation/like/entity/Like.java, backend/project2/src/main/java/com/team8/project2/domain/curation/like/repository/LikeRepository.java, backend/project2/src/main/java/com/team8/project2/domain/member/controller/ApiV1MemberController.java, backend/project2/src/main/java/com/team8/project2/global/RedisUtils.java, backend/project2/src/test/java/com/team8/project2/domain/curation/controller/LikeConcurrencyTest.java, backend/project2/src/test/java/com/team8/project2/domain/curation/service/CurationServiceTest.java
좋아요 기능 동시성 문제 방지 테스트 코드 추가 및 구현 완료
=> Refactor/좋아요 동시성 처리

frontend/project2/app/components/post-list.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/curation/following/page.tsx
큐레이션 목록 페이지, 큐레이션 상세 페이지에서 링크 메타데이터를 계속 요청하는 오류 해결
=> Hotfix/프론트 메타데이터 요청 오류 수정

backend/project2/src/main/java/com/team8/project2/domain/member/controller/ApiV1MemberController.java, backend/project2/src/main/java/com/team8/project2/domain/member/event/ProfileImageUpdateEvent.java, backend/project2/src/main/java/com/team8/project2/domain/member/service/MemberService.java, backend/project2/src/main/java/com/team8/project2/domain/member/service/ProfileImageEventListener.java, backend/project2/src/main/java/com/team8/project2/global/init/BaseInitData.java, frontend/project2/app/components/headerWrapper.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/curation/following/page.tsx, frontend/project2/app/following/page.tsx, frontend/project2/app/profile/page.tsx
- /profile 페이지에서 프로필 이미지 변경(업로드) 기능 추가
- 프로필 이미지가 변경되면 기존 이미지는 비동기 삭제 처리
- 기본 이미지 적용 `(s3Uploader.getBaseUrl() + "default-profile.svg")`
- 프론트 링크 메타 데이터 요청 최적화
- 큐레이션, 댓글 샘플 데이터 추가
- 회원가입 시 기본 이미지 지정은 추가 수정이 필요함
- (회원가입 시 초기 이미지를 받지 않도록 하는 게 좋아보입니다.)
- 이미지 업로드 시 용량 제한, 확장자 제한 추가 구현 필요
- 이미지 업로드를 테스트하려면 환경 변수로 AWS access key, secret key가 필요합니다.
Closes #122
=> Feat/#122 프로필 이미지

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/tag/dto/TagResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/tag/repository/TagRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/tag/service/TagService.java, frontend/project2/app/admin/members/page.tsx, frontend/project2/app/components/left-sidebar.tsx, frontend/project2/app/components/post-list.tsx, frontend/project2/app/home/loading.tsx, frontend/project2/app/home/page.tsx
좌측 사이드바의 트렌딩 태그 기능 구현
트렌딩 태그 기준 : 가장 많이 사용된 5개의 태그
Closes #133
=> Feat/#133 트렌딩 태그

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java
- 큐레이션 좋아요순 검색이 DB 값으로 정렬되어 실시간으로 좋아요 수를 기반으로 정렬되지 않는 오류를 수정했습니다.
- Redis로 좋아요 순 정렬되도록 수정
Closed #135
=> fix: 좋아요순 검색이 Redis의 실제 좋아요 값으로 정렬되도록 오류 수정

backend/project2/src/main/java/com/team8/project2/domain/comment/dto/CommentDto.java, frontend/project2/app/admin/members/page.tsx, frontend/project2/app/components/comment-section.tsx
댓글 작성 시 응답에 작성자의 프로필 이미지를 추가해,
댓글 작성 시 새로고침 없이 작성자의 프로필 이미지가 표시되도록 수정
Closes #137
=> Fix/#137 댓글 프로필 사진 표시 오류

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationSummaryResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/TrendingCurationResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/repository/CurationRepository.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, frontend/project2/app/components/right-sidebar.tsx
- 오늘의 인기 큐레이션 기능 추가
1일 내 조회수가 가장 많은 3개의 큐레이션을 순서대로 우측 사이드바에 표시합니다.
1일내 조회수가 없는 경우, 전체 누적 조회수가 많은 3개의 큐레이션이 표시됩니다.
Closes #139
=> Feat/#139 오늘의 인기 큐레이션

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/controller/ApiV1PlaylistController.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/dto/PlaylistDto.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/dto/PlaylistItemDto.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/dto/PlaylistItemOrderUpdateDto.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/entity/Playlist.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/entity/PlaylistItem.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/repository/PlaylistRepository.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/service/PlaylistService.java, backend/project2/src/main/java/com/team8/project2/global/security/SecurityConfig.java, backend/project2/src/test/java/com/team8/project2/domain/playlist/controller/ApiV1PlaylistControllerTest.java, frontend/project2/app/components/add-to-playlist-modal.tsx, frontend/project2/app/components/playlist-form.tsx, frontend/project2/app/components/playlist-items.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/playlists/[id]/page.tsx, frontend/project2/app/playlists/new/page.tsx, frontend/project2/lib/playlist-service.ts, frontend/project2/types/playlist.ts
큐레이션에 "플레이리스트에 추가" 기능을 구현하였습니다.
플레이리스트에서 추가된 큐레이션 확인할 수 있습니다.
=> Feat/플레이리스트에 큐레이션 추가

frontend/project2/app/components/post-list.tsx, frontend/project2/app/components/share-button.tsx, frontend/project2/app/curation/[id]/page.tsx
=> feat: 공유하기 버튼 기능 추가

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, frontend/project2/app/components/right-sidebar.tsx
오늘의 인기 큐레이션 사이드바에 총 조회수가 아닌 일간 조회수가 표시되도록 수정했습니다.
Closed #150
=> Feat/#150 오늘의 인기 큐레이션에 일간 조회수 표시

backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/entity/Curation.java, frontend/project2/app/components/post-list.tsx
글 목록 페이지에 댓글 수를 표시합니다.
Closes #152
=> Feat/#152 글 목록 페이지에 댓글 수 표시

backend/project2/src/main/java/com/team8/project2/domain/comment/controller/ApiV1CommentController.java, backend/project2/src/main/java/com/team8/project2/domain/comment/dto/ReplyCommentDto.java, backend/project2/src/main/java/com/team8/project2/domain/comment/entity/Comment.java, backend/project2/src/main/java/com/team8/project2/domain/comment/entity/ReplyComment.java, backend/project2/src/main/java/com/team8/project2/domain/comment/repository/ReplyCommentRepository.java, backend/project2/src/main/java/com/team8/project2/domain/comment/service/CommentService.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationDetailResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/service/CurationService.java, frontend/project2/app/components/comment-section.tsx, frontend/project2/app/components/headerWrapper.tsx, frontend/project2/app/curation/following/page.tsx
- 댓글 답글 기능을 추가했습니다.
답글 작성/수정/삭제
Closes #154
=> Feat/#154 댓글 답글 기능 구현

backend/project2/src/main/java/com/team8/project2/domain/admin/controller/ApiV1AdminController.java, backend/project2/src/main/java/com/team8/project2/domain/comment/controller/ApiV1CommentController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/controller/ApiV1CurationController.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationDetailResDto.java, backend/project2/src/main/java/com/team8/project2/domain/curation/curation/dto/CurationResDto.java, backend/project2/src/main/java/com/team8/project2/domain/link/controller/ApiV1LinkController.java, backend/project2/src/main/java/com/team8/project2/domain/link/entity/Link.java, backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java, frontend/project2/app/[username]/page.tsx, frontend/project2/app/components/post-list.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/playlists/page.tsx
- 링크 메타 데이터 불러오기 수정
링크 생성 시점에 메타 데이터를 로드하고, 큐레이션 전체 조회 및 특정 큐레이션 조회 시 응답에 추가되어 별도의 요청 없이 처리합니다.
Closes #156
=> Fix/#156 링크 메타 데이터 불러오기 수정

backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/controller/ApiV1PlaylistController.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/dto/PlaylistDto.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/dto/PlaylistItemUpdateDto.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/service/PlaylistService.java, frontend/project2/app/components/header.tsx, frontend/project2/app/components/playlist-items.tsx, frontend/project2/app/explore/playlists/page.tsx, frontend/project2/app/playlists/[id]/page.tsx, frontend/project2/lib/playlist-service.ts, frontend/project2/types/playlist.ts
플레이리스트에 추가한 링크의 제목, 주소, 설명을 편집할 수 있습니다.
=> Feat/링크 편집하기

frontend/project2/app/client-layout.tsx, frontend/project2/libs/backend/apiV1/schema.d.ts
=> Refactor/#158 추가기능 수행

frontend/project2/app/playlists/[id]/page.tsx
playlist 상세 보기에서 좋아요 연동 문제를 해결하지 못하고
➡️ 대신에, 상세 보기에서 좋아요 버튼을 삭제하는 방향으로 진행.
=> refactor: playlist 상세보기 좋아요 기능 삭제

backend/project2/src/main/java/com/team8/project2/domain/link/service/LinkService.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/dto/PlaylistCreateDto.java, backend/project2/src/main/java/com/team8/project2/domain/playlist/service/PlaylistService.java, backend/project2/src/main/java/com/team8/project2/global/init/BaseInitData.java, frontend/project2/app/components/like-button.tsx, frontend/project2/app/components/liked-playlist-grid.tsx, frontend/project2/app/components/playlist-grid.tsx, frontend/project2/app/components/playlist-items.tsx, frontend/project2/app/components/quill-editor.tsx, frontend/project2/app/explore/playlists/page.tsx, frontend/project2/app/playlists/[id]/page.tsx, frontend/project2/app/playlists/new/page.tsx, frontend/project2/lib/playlist-service.ts
플레이리스트 좋아요가 반영되지 않는 오류를 수정하였습니다.
플레이리스트 카드의 하단 라인이 플레이리스트 설명 길이에 따라 다르게 나오는 현상을 수정하였습니다.
BaseInitData에 플레이리스트 데이터 추가하였습니다.
=> Bug/플레이리스트 오류 수정

frontend/project2/app/components/header.tsx, frontend/project2/app/components/like-button.tsx, frontend/project2/app/components/post-list.tsx, frontend/project2/app/curation/[id]/edit/page.tsx, frontend/project2/app/curation/[id]/page.tsx, frontend/project2/app/curation/following/page.tsx
- 로그인하지 않으면 좋아요 버튼 비활성화
- 사용되지 않는 UI 제거
- 검색 필터링 버튼을 검색 창으로 변경
Closes #172
=> Refactor/#172 인증 상태에 따라 기능 잠금 처리

backend/.idea/encodings.xml, frontend/project2/app/playlists/[id]/page.tsx
플레이리스트 상세페이지에서 쿼리 파라미터가 올바르지않아 새로고침이 반복되는 생기는 문제를 수정했습니다.
=> Bug/플레이리스트 무한 새로고침

backend/project2/src/main/java/com/team8/project2/domain/comment/dto/ReplyCommentDto.java, backend/project2/src/main/java/com/team8/project2/domain/comment/entity/Comment.java, backend/project2/src/main/java/com/team8/project2/domain/comment/entity/ReplyComment.java, frontend/project2/app/api/favicon/apple-icon/route.ts, frontend/project2/app/api/favicon/icon/route.ts, frontend/project2/app/api/favicon/route.ts, frontend/project2/app/components/header.tsx, frontend/project2/app/layout.tsx, frontend/project2/app/middleware.ts, frontend/project2/public/icon.svg
답글이 있으면 댓글이 삭제 안되는 오류 수정
Closes #176
=> Fix/#176 답글이 있으면 댓글이 삭제 안되는 오류
